# Generated by Django 2.2.7 on 2019-11-24 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_word_sets', to=settings.AUTH_USER_MODEL)),
                ('starred_users', models.ManyToManyField(related_name='starred_word_sets', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(to='vocastory.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('starred_users', models.ManyToManyField(related_name='starred_stories', to=settings.AUTH_USER_MODEL)),
                ('word_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vocastory.WordSet')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_sentences', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocastory.Story')),
                ('used_words', models.ManyToManyField(to='vocastory.Word')),
            ],
        ),
    ]
