# Generated by Django 2.2.7 on 2019-11-24 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocastory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='votes',
        ),
        migrations.AddField(
            model_name='sentence',
            name='voted_users',
            field=models.ManyToManyField(related_name='voted_sentences', to=settings.AUTH_USER_MODEL),
        ),
    ]
